import { useEffect, useState } from "react"
import { useRouter } from "next/router"

import Head from "next/head"

import styles from "styles/login.module.scss"

import AppLayout from "components/AppLayout"
import Button from "components/Button"
import GitHub from "components/Icons/GitHub"
import Logo from "components/Icons/Logo"

import { loginWithGitHub, onAutStateChanged } from "firebaseservices/client"

export default function Home() {
  const [user, setUser] = useState(undefined)

  const USER_STATES = {
    NOT_LOGGED: null,
    NOT_KNOWN: undefined,
  }

  const router = useRouter()

  useEffect(() => {
    onAutStateChanged(setUser)
  }, [])

  useEffect(() => {
    user && router.replace("/home")
  }, [user])

  const handleClick = () => {
    loginWithGitHub()
  }

  return (
    <>
      <Head>
        <title>devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section className={styles["container-component"]}>
          <Logo width="100" />
          <h1>Devter</h1>
          <h2>
            Talk about development <br />
            with developers
          </h2>
          <div>
            {user === USER_STATES.NOT_LOGGED && (
              <Button onClick={handleClick}>
                <GitHub fill="#fff" width={24} height={24} />
                Login with GitHub
              </Button>
            )}
            {user === USER_STATES.NOT_KNOWNs && <img src="/spinner.gif" />}
          </div>
        </section>
      </AppLayout>
    </>
  )
}
