import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Link from "next/link";
import { useRouter } from "next/router";
import AppLayout from "../components/AppLayout";
import Button from "../components/Button";
import GitHub from "../components/Icons/GitHub";

export default function Home() {
  return (
    <>
      <Head>
        <title>devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section className={styles["container-component"]}>
          <img src="/devter-logo.png" alt="Logo" />
          <h1>Devter</h1>
          <h2>
            Talk about development <br />
            with developers
          </h2>
          <div>
            <Button>
              <GitHub fill="#fff" width={24} height={24} />
              Login with GitHub
            </Button>
          </div>
        </section>
      </AppLayout>
    </>
  );
}
